ALTER TABLE SMART_INDESIGNSERVERJOBS ADD (
  PICKUPTIME varchar(30) default '');
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_INDESIGNSERVERJOBS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
INSERT INTO SMART_CONFIG (ID, NAME, VALUE) 
SELECT SMART_CONFIG_seq.nextval ,'idsautomationpickuptime', 'yes' FROM DUAL;
