DELETE FROM SMART_PROFILEFEATURES WHERE FEATURE = 1006;

UPDATE SMART_CHANNELS SET TYPE = 'other' WHERE TYPE = 'newsfeed';

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Article' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Article');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'ArticleTemplate' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'ArticleTemplate');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Layout' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Layout');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'LayoutTemplate' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'LayoutTemplate');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Image' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Image');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Advert' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Advert');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'AdvertTemplate' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'AdvertTemplate');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Plan' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Plan');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Audio' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Audio');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Video' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Video');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Library' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Library');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Dossier' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Dossier');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'DossierTemplate' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'DossierTemplate');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'LayoutModule' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'LayoutModule');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'LayoutModuleTemplate' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'LayoutModuleTemplate');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Task' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Task');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Hyperlink' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Hyperlink');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Spreadsheet' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Spreadsheet');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Other' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'Other');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'PublishForm' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'PublishForm');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'PublishFormTemplate' WHERE PARENT IN ( SELECT ID FROM SMART_OBJECTS WHERE TYPE = 'PublishFormTemplate');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Article' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Article');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'ArticleTemplate' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'ArticleTemplate');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Layout' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Layout');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'LayoutTemplate' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'LayoutTemplate');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Image' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Image');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Advert' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Advert');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'AdvertTemplate' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'AdvertTemplate');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Plan' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Plan');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Audio' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Audio');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Video' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Video');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Library' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Library');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Dossier' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Dossier');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'DossierTemplate' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'DossierTemplate');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'LayoutModule' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'LayoutModule');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'LayoutModuleTemplate' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'LayoutModuleTemplate');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Task' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Task');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Hyperlink' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Hyperlink');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Spreadsheet' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Spreadsheet');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'Other' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'Other');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'PublishForm' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'PublishForm');

UPDATE SMART_OBJECTRELATIONS SET PARENTTYPE = 'PublishFormTemplate' WHERE PARENT IN ( SELECT ID FROM SMART_DELETEDOBJECTS WHERE TYPE = 'PublishFormTemplate');

