ALTER TABLE SMART_INDESIGNSERVERJOBS ADD (
  MAXSERVERMAJORVERSION int default '0',
  MAXSERVERMINORVERSION int default '0');
ALTER TABLE SMART_INDESIGNSERVERJOBS RENAME COLUMN SERVERMAJORVERSION TO SERVERMAJORVERSION_OLD;
ALTER TABLE SMART_INDESIGNSERVERJOBS ADD (
  MINSERVERMAJORVERSION int default '0');
UPDATE SMART_INDESIGNSERVERJOBS SET MINSERVERMAJORVERSION = SERVERMAJORVERSION_OLD;
ALTER TABLE SMART_INDESIGNSERVERJOBS DROP (SERVERMAJORVERSION_OLD) CASCADE CONSTRAINTS;
ALTER TABLE SMART_INDESIGNSERVERJOBS RENAME COLUMN SERVERMINORVERSION TO SERVERMINORVERSION_OLD;
ALTER TABLE SMART_INDESIGNSERVERJOBS ADD (
  MINSERVERMINORVERSION int default '0');
UPDATE SMART_INDESIGNSERVERJOBS SET MINSERVERMINORVERSION = SERVERMINORVERSION_OLD;
ALTER TABLE SMART_INDESIGNSERVERJOBS DROP (SERVERMINORVERSION_OLD) CASCADE CONSTRAINTS;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_INDESIGNSERVERJOBS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
INSERT INTO SMART_CONFIG (ID, NAME, VALUE) 
SELECT SMART_CONFIG_seq.nextval ,'ids2014ccsupport', 'yes' FROM DUAL;
