ALTER TABLE SMART_AUTHORIZATIONS ADD (
  BUNDLE int default '0');
ALTER TABLE SMART_DELETEDOBJECTS ADD (
  ORIENTATION int default '0');
ALTER TABLE SMART_DELETEDOBJECTS MODIFY (  DPI real default '0' );
ALTER TABLE SMART_OBJECTS ADD (
  ORIENTATION int default '0');
ALTER TABLE SMART_OBJECTS MODIFY (  DPI real default '0' );
ALTER TABLE SMART_OBJECTVERSIONS ADD (
  ORIENTATION int default '0');
ALTER TABLE SMART_OBJECTVERSIONS MODIFY (  DPI real default '0' );
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_INDESIGNARTICLES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_IDARTICLESPLACEMENTS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_TERMS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_MTP_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_MTPSENTOBJECTS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_OBJECTFLAGS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;

CREATE TABLE SMART_PUBLISHEDPLCMTSHIST (
  ID int ,
  OBJECTID int default '0',
  PUBLISHID int default '0',
  MAJORVERSION int default '0',
  MINORVERSION int default '0',
  EXTERNALID varchar(200) default '',
  PLACEMENTHASH varchar(64),
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PUBLISHEDPLCMTSHIST_SEQ START WITH 100;
CREATE  INDEX OBPU_PUBLPLCHIST on SMART_PUBLISHEDPLCMTSHIST(OBJECTID, PUBLISHID) ;
CREATE  INDEX PUOB_PUBLPLCHIST on SMART_PUBLISHEDPLCMTSHIST(PUBLISHID, OBJECTID) ;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_INDESIGNSERVERJOBS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_SERVERJOBS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_SERVERJOBTYPESONHOLD_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_OBJECTRELATIONLABELS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SMART_CHANNELDATA_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
UPDATE SMART_CONFIG set VALUE = '10.1' where NAME = 'version';
