CREATE TABLE SMART_ACTIONPROPERTIES (
  ID int ,
  PUBLICATION int default '0',
  ORDERID int default '0',
  PROPERTY varchar(200) default '',
  EDIT  varchar(2) default '',
  MANDATORY  varchar(2) default '',
  ACTION varchar(40) default '',
  TYPE varchar(40) default '',
  RESTRICTED  varchar(2) default '',
  REFRESHONCHANGE  varchar(2) default '',
  PARENTFIELDID int default '0',
  DOCUMENTID varchar(512) default '',
  INITIALHEIGHT int default '0',
  MULTIPLEOBJECTS  varchar(2) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_ACTIONPROPERTIES_SEQ START WITH 100;
CREATE  INDEX PBAC_ACTIONPROPERTIES on SMART_ACTIONPROPERTIES(PUBLICATION, ACTION) ;

CREATE TABLE SMART_AUTHORIZATIONS (
  ID int ,
  GRPID int default '0',
  PUBLICATION int default '0',
  SECTION int default '0',
  STATE int default '0',
  RIGHTS varchar(40) default '',
  ISSUE int default '0',
  PROFILE int default '0',
  BUNDLE int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_AUTHORIZATIONS_SEQ START WITH 100;
CREATE  INDEX GIPU_AUTHORIZATIONS on SMART_AUTHORIZATIONS(GRPID, PUBLICATION) ;
CREATE  INDEX GIPR_AUTHORIZATIONS on SMART_AUTHORIZATIONS(GRPID, PROFILE) ;
INSERT INTO SMART_AUTHORIZATIONS (ID, GRPID, PUBLICATION, SECTION, STATE, RIGHTS, ISSUE, PROFILE, BUNDLE) VALUES (1, 2, 1, 0, 0, 'VRWDCKSF', 0, 1);

CREATE TABLE SMART_CONFIG (
  ID int ,
  NAME varchar(200) default '',
  VALUE  clob,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_CONFIG_SEQ START WITH 100;
INSERT INTO SMART_CONFIG (ID, NAME, VALUE) VALUES (1, 'version', '00');

CREATE TABLE SMART_DELETEDOBJECTS (
  ID int ,
  DOCUMENTID varchar(512) default '',
  TYPE varchar(20) default '',
  NAME varchar(255) default '',
  PUBLICATION int default '0',
  ISSUE int default '0',
  SECTION int default '0',
  STATE int default '0',
  ROUTETO varchar(255) default '',
  COPYRIGHT varchar(255) default '',
  SLUGLINE varchar(255) default '',
  COMMENTS varchar(255) default '',
  AUTHOR varchar(255) default '',
  DEADLINE varchar(30) default '',
  URGENCY varchar(40) default '',
  FORMAT varchar(128) default '',
  WIDTH real default '0',
  DEPTH real default '0',
  DPI int default '0',
  LENGTHWORDS int default '0',
  LENGTHCHARS int default '0',
  LENGTHPARAS int default '0',
  LENGTHLINES int default '0',
  KEYWORDS  clob,
  MODIFIER varchar(40) default '',
  MODIFIED varchar(30) default '',
  CREATOR varchar(40) default '',
  CREATED varchar(30) default '',
  DELETOR varchar(40) default '',
  DELETED varchar(30) default '',
  COPYRIGHTMARKED varchar(255) default '',
  COPYRIGHTURL varchar(255) default '',
  CREDIT varchar(255) default '',
  SOURCE varchar(255) default '',
  DESCRIPTION  clob,
  DESCRIPTIONAUTHOR varchar(255) default '',
  NRCOLUMNS int default '0',
  PLAINCONTENT  clob,
  FILESIZE int default '0',
  COLORSPACE varchar(20) default '',
  PAGENUMBER int default '0',
  TYPES  clob,
  STORENAME  clob,
  PAGERANGE varchar(50) default '',
  HIGHRESFILE varchar(255) default '',
  DEADLINESOFT varchar(30) default '',
  DEADLINECHANGED  varchar(1) default '',
  PLANNEDPAGERANGE varchar(50) default '',
  MAJORVERSION int default '-1',
  MINORVERSION int default '0',
  ENCODING varchar(100) default '',
  COMPRESSION varchar(100) default '',
  KEYFRAMEEVERYFRAMES int default '0',
  CHANNELS varchar(100) default '',
  ASPECTRATIO varchar(100) default '',
  CONTENTSOURCE varchar(100) default '',
  RATING int default 0,
  INDEXED  varchar(2) default '',
  CLOSED  varchar(2) default '',
  ROUTETOUSERID int default '0',
  ROUTETOGROUPID int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_DELETEDOBJECTS_SEQ START WITH 100;

CREATE TABLE SMART_GROUPS (
  ID int ,
  NAME varchar(100) default '',
  DESCR varchar(255) default '',
  ADMIN  varchar(2) default '',
  ROUTING  varchar(2) default '',
  EXTERNALID varchar(200) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_GROUPS_SEQ START WITH 100;
CREATE  INDEX IDNARO_GROUPS on SMART_GROUPS(ID, NAME, ROUTING) ;
CREATE  INDEX NA_GROUPS on SMART_GROUPS(NAME) ;
INSERT INTO SMART_GROUPS (ID, NAME, DESCR, ADMIN, ROUTING, EXTERNALID) VALUES (2, 'admin', 'System Admins', 'on', '', '');

CREATE TABLE SMART_LOG (
  ID int ,
  USERNAME varchar(50) default '',
  SERVICE varchar(50) default '',
  IP varchar(30) default '',
  DATED varchar(30) default '',
  OBJECTID int default '0',
  PUBLICATION int default '0',
  ISSUE int default '0',
  SECTION int default '0',
  STATE int default '0',
  PARENT int default '0',
  LOCKED varchar(1) default '',
  RENDITION varchar(10) default '',
  TYPE varchar(20) default '',
  ROUTETO varchar(255) default '',
  EDITION varchar(255) default '',
  MINORVERSION int default '0',
  CHANNELID int default '0',
  MAJORVERSION int default '-1',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_LOG_SEQ START WITH 100;

CREATE TABLE SMART_NAMEDQUERIES (
  ID int ,
  QUERY varchar(200) default '',
  INTERFACE  clob,
  SQL  clob,
  COMMENTS  clob,
  CHECKACCESS varchar(2) default 'on',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_NAMEDQUERIES_SEQ START WITH 100;
CREATE  INDEX QE_NAMEDQUERIES on SMART_NAMEDQUERIES(QUERY) ;
INSERT INTO SMART_NAMEDQUERIES (ID, QUERY, INTERFACE, SQL, COMMENTS, CHECKACCESS) VALUES (2, 'Templates', '', '/*SELECT*/
select o.ID as "ID", o.TYPE as "Type", o.NAME as "Name", st.STATE as "State", ul.FULLNAME as "LockedBy", p.PUBLICATION as "Publication", s.SECTION as "Section", o.COMMENTS as "Comment", o.ROUTETO as "RouteTo", un.FULLNAME as "Creator", o.FORMAT as "Format", um.FULLNAME as "Modifier", p.ID as "PublicationId", s.ID as "SectionId", st.ID as "StateId", st.COLOR as "StateColor", l.LOCKOFFLINE as "LockForOffline"
/*FROM*/
from SMART_OBJECTS o
/*JOINS*/
left join SMART_PUBLICATIONS p on (o.PUBLICATION = p.ID)
left join SMART_PUBLSECTIONS s on (o.SECTION = s.ID)
left join SMART_STATES st on (o.STATE = st.ID)
left join SMART_OBJECTLOCKS l on (o.ID = l.OBJECT)
left join SMART_USERS ul on (l.USR = ul.USERNAME)
left join SMART_USERS um on (o.MODIFIER = um.USERNAME)
left join SMART_USERS un on (o.CREATOR = un.USERNAME)
/*WHERE*/
where (o.TYPE = ''LayoutTemplate'' or o.TYPE = ''ArticleTemplate'' or o.TYPE = ''LayoutModuleTemplate'')', 'Shows all layout templates.', 'on');
INSERT INTO SMART_NAMEDQUERIES (ID, QUERY, INTERFACE, SQL, COMMENTS, CHECKACCESS) VALUES (5, 'Libraries', '', '/*SELECT*/
select o.ID as "ID", o.TYPE as "Type", o.NAME as "Name", st.STATE as "State", ul.FULLNAME as "LockedBy", p.PUBLICATION as "Publication", s.SECTION as "Section", o.COMMENTS as "Comment", o.ROUTETO as "RouteTo", un.FULLNAME as "Creator", o.FORMAT as "Format", um.FULLNAME as "Modifier", p.ID as "PublicationId", s.ID as "SectionId", st.ID as "StateId", st.COLOR as "StateColor", l.LOCKOFFLINE as "LockForOffline"
/*FROM*/
from SMART_OBJECTS o
/*JOINS*/
left join SMART_PUBLICATIONS p on (o.PUBLICATION = p.ID)
left join SMART_PUBLSECTIONS s on (o.SECTION = s.ID)
left join SMART_STATES st on (o.STATE = st.ID)
left join SMART_OBJECTLOCKS l on (o.ID = l.OBJECT)
left join SMART_USERS ul on (l.USR = ul.USERNAME)
left join SMART_USERS um on (o.MODIFIER = um.USERNAME)
left join SMART_USERS un on (o.CREATOR = un.USERNAME)
/*WHERE*/
where (o.TYPE = ''Library'')', 'Shows all libraries.', 'on');

CREATE TABLE SMART_OBJECTLOCKS (
  ID int ,
  OBJECT int default '0',
  USR varchar(40) default '',
  TIMESTAMP timestamp,
  IP varchar(30) default '',
  LOCKOFFLINE varchar(2) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_OBJECTLOCKS_SEQ START WITH 100;
CREATE UNIQUE INDEX OB_OBJECTLOCKS on SMART_OBJECTLOCKS(OBJECT) ;
CREATE  INDEX OBUSR_OBJECTLOCKS on SMART_OBJECTLOCKS(OBJECT, USR) ;

CREATE TABLE SMART_OBJECTRELATIONS (
  ID int ,
  PARENT int default '0',
  CHILD int default '0',
  TYPE varchar(40) default '',
  SUBID varchar(20) default '',
  PAGERANGE varchar(50) default '',
  RATING int default 0,
  PARENTTYPE varchar(20) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_OBJECTRELATIONS_SEQ START WITH 100;
CREATE UNIQUE INDEX CH_OBJECTRELATIONS on SMART_OBJECTRELATIONS(PARENT, CHILD, SUBID, TYPE) ;
CREATE  INDEX PACHTY_OBJECTRELATIONS on SMART_OBJECTRELATIONS(PARENT, CHILD, TYPE) ;
CREATE  INDEX CHILD_TYPE_ID on SMART_OBJECTRELATIONS(CHILD, TYPE, ID) ;

CREATE TABLE SMART_OBJECTS (
  ID int ,
  DOCUMENTID varchar(512) default '',
  TYPE varchar(20) default '',
  NAME varchar(255) default '',
  PUBLICATION int default '0',
  ISSUE int default '0',
  SECTION int default '0',
  STATE int default '0',
  ROUTETO varchar(255) default '',
  COPYRIGHT varchar(255) default '',
  SLUGLINE varchar(255) default '',
  COMMENTS varchar(255) default '',
  AUTHOR varchar(255) default '',
  DEADLINE varchar(30) default '',
  URGENCY varchar(40) default '',
  FORMAT varchar(128) default '',
  WIDTH real default '0',
  DEPTH real default '0',
  DPI int default '0',
  LENGTHWORDS int default '0',
  LENGTHCHARS int default '0',
  LENGTHPARAS int default '0',
  LENGTHLINES int default '0',
  KEYWORDS  clob,
  MODIFIER varchar(40) default '',
  MODIFIED varchar(30) default '',
  CREATOR varchar(40) default '',
  CREATED varchar(30) default '',
  DELETOR varchar(40) default '',
  DELETED varchar(30) default '',
  COPYRIGHTMARKED varchar(255) default '',
  COPYRIGHTURL varchar(255) default '',
  CREDIT varchar(255) default '',
  SOURCE varchar(255) default '',
  DESCRIPTION  clob,
  DESCRIPTIONAUTHOR varchar(255) default '',
  NRCOLUMNS int default '0',
  PLAINCONTENT  clob,
  FILESIZE int default '0',
  COLORSPACE varchar(20) default '',
  TYPES  clob,
  PAGENUMBER int default '0',
  STORENAME  clob,
  PAGERANGE varchar(50) default '',
  HIGHRESFILE varchar(255) default '',
  DEADLINESOFT varchar(30) default '',
  DEADLINECHANGED  varchar(1) default '',
  PLANNEDPAGERANGE varchar(50) default '',
  MAJORVERSION int default '-1',
  MINORVERSION int default '0',
  ENCODING varchar(100) default '',
  COMPRESSION varchar(100) default '',
  KEYFRAMEEVERYFRAMES int default '0',
  CHANNELS varchar(100) default '',
  ASPECTRATIO varchar(100) default '',
  CONTENTSOURCE varchar(100) default '',
  RATING int default 0,
  INDEXED  varchar(2) default '',
  CLOSED  varchar(2) default '',
  ROUTETOUSERID int default '0',
  ROUTETOGROUPID int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_OBJECTS_SEQ START WITH 100;
CREATE  INDEX NM_OBJECTS on SMART_OBJECTS(NAME) ;
CREATE  INDEX PBSECTSTATE_OBJECTS on SMART_OBJECTS(PUBLICATION, SECTION, STATE, CLOSED) ;
CREATE  INDEX PUBID_OBJECTS on SMART_OBJECTS(PUBLICATION, ID, CLOSED) ;
CREATE  INDEX MO_OBJECTS on SMART_OBJECTS(MODIFIER) ;
CREATE  INDEX PC_OBJECTS on SMART_OBJECTS(PLAINCONTENT) INDEXTYPE IS CTXSYS.CONTEXT PARAMETERS ('');
CREATE  INDEX ROID_OBJECTS on SMART_OBJECTS(ROUTETO, ID, CLOSED) ;
CREATE  INDEX CODO_OBJECTS on SMART_OBJECTS(CONTENTSOURCE, DOCUMENTID) ;

CREATE TABLE SMART_OBJECTVERSIONS (
  ID int ,
  OBJID int default '0',
  MINORVERSION int default '0',
  MODIFIER varchar(40) default '',
  COMMENTS varchar(255) default '',
  SLUGLINE varchar(255) default '',
  CREATED varchar(30) default '',
  TYPES  clob,
  FORMAT varchar(128) default '',
  WIDTH real default '0',
  DEPTH real default '0',
  DPI int default '0',
  LENGTHWORDS int default '0',
  LENGTHCHARS int default '0',
  LENGTHPARAS int default '0',
  LENGTHLINES int default '0',
  KEYWORDS  clob,
  DESCRIPTION  clob,
  DESCRIPTIONAUTHOR varchar(255) default '',
  NRCOLUMNS int default '0',
  PLAINCONTENT  clob,
  FILESIZE int default '0',
  COLORSPACE varchar(20) default '',
  STATE int default '0',
  MAJORVERSION int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_OBJECTVERSIONS_SEQ START WITH 100;
CREATE  INDEX OIVE_OBJECTVERSIONS on SMART_OBJECTVERSIONS(OBJID, MAJORVERSION, MINORVERSION) ;

CREATE TABLE SMART_OBJECTRENDITIONS (
  ID int ,
  OBJID int default '0',
  EDITIONID int default '0',
  RENDITION varchar(10) default '',
  FORMAT varchar(128) default '',
  MAJORVERSION int default '0',
  MINORVERSION int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_OBJECTRENDITIONS_SEQ START WITH 100;
CREATE  INDEX OBED_OBJECTRENDITIONS on SMART_OBJECTRENDITIONS(OBJID, EDITIONID, RENDITION) ;

CREATE TABLE SMART_PAGES (
  ID int ,
  OBJID int default '0',
  WIDTH real default '0',
  HEIGHT real default '0',
  PAGENUMBER varchar(20) default '',
  PAGEORDER int default '0',
  NR int default '0',
  TYPES  clob,
  EDITION int default '0',
  MASTER varchar(255) default '',
  INSTANCE varchar(40) default 'Production',
  PAGESEQUENCE int default '0',
  ORIENTATION varchar(9) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PAGES_SEQ START WITH 100;
CREATE  INDEX OBPAED_PAGES on SMART_PAGES(OBJID, PAGEORDER, EDITION) ;

CREATE TABLE SMART_PLACEMENTS (
  ID int ,
  PARENT int default '0',
  CHILD int default '0',
  PAGE int default '0',
  ELEMENT varchar(200) default '',
  ELEMENTID varchar(200) default '',
  FRAMEORDER int default '0',
  FRAMEID varchar(200) default '',
  LEFTPOS real default '0',
  TOP real default '0',
  WIDTH real default '0',
  HEIGHT real default '0',
  OVERSET real default '0',
  OVERSETCHARS int default '0',
  OVERSETLINES int default '0',
  LAYER varchar(200) default '',
  CONTENT  clob,
  TYPE varchar(40),
  EDITION int default '0',
  CONTENTDX real default 0,
  CONTENTDY real default 0,
  SCALEX real default 1,
  SCALEY real default 1,
  PAGESEQUENCE int default '0',
  PAGENUMBER varchar(20) default '',
  FORMWIDGETID varchar(200) default '',
  FRAMETYPE varchar(20) default '',
  SPLINEID varchar(200) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PLACEMENTS_SEQ START WITH 100;
CREATE  INDEX PACHTY_PLACEMENTS on SMART_PLACEMENTS(PARENT, CHILD, TYPE) ;
CREATE  INDEX EI_PLACEMENTS on SMART_PLACEMENTS(ELEMENTID) ;
CREATE  INDEX CHTY_PLACEMENTS on SMART_PLACEMENTS(CHILD, TYPE) ;

CREATE TABLE SMART_ELEMENTS (
  ID int ,
  GUID varchar(200) default '',
  NAME varchar(200) default '',
  OBJID int default 0,
  LENGTHWORDS int default '0',
  LENGTHCHARS int default '0',
  LENGTHPARAS int default '0',
  LENGTHLINES int default '0',
  SNIPPET varchar(255) default '',
  VERSION varchar(50) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_ELEMENTS_SEQ START WITH 100;
CREATE  INDEX OIGU_ELEMENTS on SMART_ELEMENTS(OBJID, GUID) ;

CREATE TABLE SMART_INDESIGNARTICLES (
  OBJID int default 0,
  ARTUID varchar(40) default '',
  NAME varchar(200) default '',
  CODE int default '0',
  PRIMARY KEY (OBJID, ARTUID)
);

CREATE TABLE SMART_IDARTICLESPLACEMENTS (
  OBJID int default 0,
  ARTUID varchar(40) default '',
  PLCID int default 0,
  PRIMARY KEY (OBJID, ARTUID, PLCID)
);

CREATE TABLE SMART_OBJECTOPERATIONS (
  ID int ,
  OBJID int default 0,
  GUID varchar(40) default '',
  TYPE varchar(200) default '',
  NAME varchar(200) default '',
  PARAMS  clob,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_OBJECTOPERATIONS_SEQ START WITH 100;
CREATE  INDEX OBJID_OBJECTOPERATIONS on SMART_OBJECTOPERATIONS(OBJID) ;

CREATE TABLE SMART_PROPERTIES (
  ID int ,
  PUBLICATION int default '0',
  OBJTYPE varchar(40) default '',
  NAME varchar(200) default '',
  DISPNAME varchar(200) default '',
  CATEGORY varchar(200) default '',
  TYPE varchar(40) default '',
  DEFAULTVALUE varchar(200) default '',
  VALUELIST  clob,
  MINVALUE varchar(200) default '',
  MAXVALUE varchar(200) default '',
  MAXLEN int default '0',
  DBUPDATED int default '0',
  ENTITY varchar(20) default 'Object',
  SERVERPLUGIN varchar(64) default '',
  ADMINUI varchar(2) default 'on',
  PROPERTYVALUES  clob,
  MINRESOLUTION varchar(200) default '',
  MAXRESOLUTION varchar(200) default '',
  PUBLISHSYSTEM varchar(64) default '',
  TEMPLATEID int default 0,
  TERMENTITYID int default '0',
  SUGGESTIONENTITY varchar(200) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PROPERTIES_SEQ START WITH 100;
CREATE  INDEX PUOB_PROPERTIES on SMART_PROPERTIES(PUBLICATION, OBJTYPE) ;
CREATE  INDEX PUDB_PROPERTIES on SMART_PROPERTIES(PUBLICATION, DBUPDATED) ;

CREATE TABLE SMART_PUBLADMIN (
  ID int ,
  PUBLICATION int default '0',
  GRPID int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PUBLADMIN_SEQ START WITH 100;
CREATE  INDEX PUGI_PUBLADMIN on SMART_PUBLADMIN(PUBLICATION, GRPID) ;

CREATE TABLE SMART_PUBLICATIONS (
  ID int ,
  PUBLICATION varchar(255) default '',
  CODE int default '0',
  EMAIL  varchar(2) default '',
  DESCRIPTION  clob,
  READINGORDERREV varchar(2) default '',
  AUTOPURGE int default 0,
  DEFAULTCHANNELID int default '0',
  CALCULATEDEADLINES  varchar(2) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PUBLICATIONS_SEQ START WITH 100;
CREATE  INDEX PB_PUBLICATIONS on SMART_PUBLICATIONS(PUBLICATION) ;
CREATE  INDEX IDPB_PUBLICATIONS on SMART_PUBLICATIONS(ID, PUBLICATION) ;
INSERT INTO SMART_PUBLICATIONS (ID, PUBLICATION, CODE, EMAIL, DESCRIPTION, READINGORDERREV, AUTOPURGE, DEFAULTCHANNELID, CALCULATEDEADLINES) VALUES (1, 'WW News', 0, '', '', '', 0, 1, '');

CREATE TABLE SMART_PUBLSECTIONS (
  ID int ,
  PUBLICATION int default '0',
  SECTION varchar(255) default '',
  ISSUE int default '0',
  CODE int default '0',
  DESCRIPTION  clob,
  PAGES int default '0',
  DEADLINE varchar(30) default '',
  DEADLINERELATIVE int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PUBLSECTIONS_SEQ START WITH 100;
CREATE  INDEX PBIS_PUBLSECTIONS on SMART_PUBLSECTIONS(PUBLICATION, ISSUE) ;
CREATE  INDEX SE_PUBLSECTIONS on SMART_PUBLSECTIONS(SECTION) ;
INSERT INTO SMART_PUBLSECTIONS (ID, PUBLICATION, SECTION, ISSUE, CODE, DESCRIPTION, PAGES, DEADLINE, DEADLINERELATIVE) VALUES (1, 1, 'News', 0, 10, '', 0, '', 0 );
INSERT INTO SMART_PUBLSECTIONS (ID, PUBLICATION, SECTION, ISSUE, CODE, DESCRIPTION, PAGES, DEADLINE, DEADLINERELATIVE) VALUES (2, 1, 'Sport', 0, 20, '', 0, '', 0 );

CREATE TABLE SMART_PUBLOBJECTS (
  ID int ,
  PUBLICATIONID int default '0',
  ISSUEID int default '0',
  OBJECTID int default '0',
  GRPID int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PUBLOBJECTS_SEQ START WITH 100;
CREATE UNIQUE INDEX PUISOBGR_PUBLOBJECTS on SMART_PUBLOBJECTS(PUBLICATIONID, ISSUEID, OBJECTID, GRPID) ;

CREATE TABLE SMART_ISSUEEDITIONS (
  ID int ,
  ISSUE int default '0',
  EDITION int default '0',
  DEADLINE varchar(30) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_ISSUEEDITIONS_SEQ START WITH 100;
CREATE  INDEX IS_ISSUEEDITIONS on SMART_ISSUEEDITIONS(ISSUE) ;
CREATE  INDEX ED_ISSUEEDITIONS on SMART_ISSUEEDITIONS(EDITION) ;

CREATE TABLE SMART_ROUTING (
  ID int ,
  PUBLICATION int default '0',
  SECTION int default '0',
  STATE int default '0',
  ROUTETO varchar(255) default '',
  ISSUE int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_ROUTING_SEQ START WITH 100;
CREATE  INDEX PBISSE_ROUTING on SMART_ROUTING(PUBLICATION, ISSUE, SECTION) ;
CREATE  INDEX ST_ROUTING on SMART_ROUTING(STATE) ;

CREATE TABLE SMART_SETTINGS (
  ID int ,
  USERNAME varchar(200) default '',
  SETTING varchar(200) default '',
  VALUE  clob,
  APPNAME varchar(200) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_SETTINGS_SEQ START WITH 100;
CREATE  INDEX US_SETTINGS on SMART_SETTINGS(USERNAME) ;
CREATE  INDEX SE_SETTINGS on SMART_SETTINGS(SETTING) ;

CREATE TABLE SMART_STATES (
  ID int ,
  PUBLICATION int default '0',
  TYPE varchar(40) default '',
  STATE varchar(40) default '',
  PRODUCE  varchar(2) default '',
  COLOR varchar(11) default '',
  NEXTSTATE int default '0',
  CODE int default '0',
  ISSUE int default '0',
  SECTION int default '0',
  DEADLINESTATE int default '0',
  DEADLINERELATIVE int default '0',
  CREATEPERMANENTVERSION  varchar(2) default '',
  REMOVEINTERMEDIATEVERSIONS  varchar(2) default '',
  READYFORPUBLISHING  varchar(2) default '',
  AUTOMATICALLYSENDTONEXT  varchar(2) default '',
  PHASE varchar(40) default 'Production',
  SKIPIDSA  varchar(2) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_STATES_SEQ START WITH 100;
CREATE  INDEX ST_STATES on SMART_STATES(STATE) ;
CREATE  INDEX PBISTYSE_STATES on SMART_STATES(PUBLICATION, ISSUE, TYPE, SECTION) ;
CREATE  INDEX ISTYSE_STATES on SMART_STATES(ISSUE, TYPE, SECTION) ;
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (1, 1, 'Article', 'Draft text', '', '#FF0000', 2, 10, 0, 0,0,0, '', '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (2, 1, 'Article', 'Ready', '', '#00FF00', 0, 20, 0, 0,0,0, '', '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (3, 1, 'Layout', 'Layouts', '', '#0000FF', 0, 0, 0, 0,0,0, '', '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (4, 1, 'LayoutTemplate', 'Layout Templates', '', '#FFFF99', 0, 0, 0, 0,0,0, '', '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (5, 1, 'ArticleTemplate', 'Article Templates', '', '#FFFF99', 0, 0, 0, 0,0,0, '', '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (6, 1, 'Image', 'Images', '', '#FFFF00', 0, 0, 0, 0,0,0, '', '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (7, 1, 'Advert', 'Adverts', '', '#99CCFF', 0, 0, 0, 0, 0, 0, '', '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (8, 1, 'Video', 'Videos', '', '#FFFF00', 0, 0, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (9, 1, 'Audio', 'Audios', '', '#FFFF00', 0, 0, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (10, 1, 'Library', 'Libraries', '', '#888888', 0, 0, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (11, 1, 'Dossier', 'Dossiers', '', '#BBBBBB', 0, 0, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (12, 1, 'DossierTemplate', 'Dossier Templates', '', '#BBBBBB', 0, 0, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (13, 1, 'LayoutModule', 'Layout Modules', '', '#D7C101', 0, 0, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (14, 1, 'LayoutModuleTemplate', 'Layout Module Templates', '', '#FFE553', 0, 0, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (15, 1, 'Task', 'Assigned', '', '#AAAAAA', 15, 10, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (16, 1, 'Task', 'In progress', '', '#AAAAAA', 16, 20, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (17, 1, 'Task', 'Completed', '', '#AAAAAA', 0, 30, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (18, 1, 'Hyperlink', 'Hyperlinks', '', '#AAAAAA', 0, 30, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (19, 1, 'Other', 'Others', '', '#AAAAAA', 0, 30, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (20, 1, 'Archive', 'Archives', '', '#AAAAAA', 0, 30, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (21, 1, 'Presentation', 'Presentations', '', '#AAAAAA', 0, 30, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (22, 1, 'Spreadsheet', 'Draft', '', '#FF0000', 23, 10, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (23, 1, 'Spreadsheet', 'Ready', '', '#00FF00', 0, 20, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (24, 1, 'PublishForm', 'Publish Forms', '', '#AAAAAA', 0, 0, 0, 0, 0, 0, 0, '', '', '', 'Production', '');
INSERT INTO SMART_STATES (ID, PUBLICATION, TYPE, STATE, PRODUCE, COLOR, NEXTSTATE, CODE, ISSUE, SECTION, DEADLINESTATE, DEADLINERELATIVE, CREATEPERMANENTVERSION, REMOVEINTERMEDIATEVERSIONS, READYFORPUBLISHING, AUTOMATICALLYSENDTONEXT, PHASE, SKIPIDSA) VALUES (25, 1, 'PublishFormTemplate', 'Publish Form Templates', '', '#AAAAAA', 0, 0, 0, 0, 0, 0, 0, '', '', '', 'Production', '');

CREATE TABLE SMART_TICKETS (
  ID int ,
  TICKETID varchar(40) default '',
  USR varchar(40) default '',
  DB varchar(255) default '',
  CLIENTNAME varchar(255) default '',
  CLIENTIP varchar(40) default '',
  APPNAME varchar(200) default '',
  APPVERSION varchar(200) default '',
  APPSERIAL varchar(200) default '',
  LOGON varchar(20) default '',
  EXPIRE varchar(30) default '',
  APPPRODUCTCODE varchar(40) default '',
  MASTERTICKETID varchar(40) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_TICKETS_SEQ START WITH 100;
CREATE  INDEX TI_TICKETS on SMART_TICKETS(TICKETID) ;
CREATE  INDEX US_TICKETS on SMART_TICKETS(USR) ;
CREATE  INDEX MTID_TICKETS on SMART_TICKETS(MASTERTICKETID) ;

CREATE TABLE SMART_TERMENTITIES (
  ID int ,
  NAME varchar(255) default '',
  PROVIDER varchar(40) default '',
  PUBLISHSYSTEMID varchar(40) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_TERMENTITIES_SEQ START WITH 100;
CREATE  INDEX TE_NAME on SMART_TERMENTITIES(NAME) ;
CREATE  INDEX TE_PROVIDER on SMART_TERMENTITIES(PROVIDER) ;
CREATE  INDEX TE_TERMENTITY on SMART_TERMENTITIES(NAME, PROVIDER) ;

CREATE TABLE SMART_TERMS (
  ENTITYID int default '0',
  DISPLAYNAME varchar(255) default '',
  NORMALIZEDNAME varchar(255) default '',
  LIGATURES varchar(255) default '',
  PRIMARY KEY (ENTITYID, DISPLAYNAME)
);
CREATE  INDEX TM_ENTITYID on SMART_TERMS(ENTITYID) ;
CREATE  INDEX TM_NORMALIZEDNAME on SMART_TERMS(ENTITYID, NORMALIZEDNAME) ;

CREATE TABLE SMART_USERS (
  ID int ,
  USERNAME varchar(40) default '',
  FULLNAME varchar(255) default '',
  PASS varchar(128) default '',
  DISABLE  varchar(2) default '',
  FIXEDPASS  varchar(2) default '',
  EMAIL varchar(100) default '',
  EMAILGRP  varchar(2) default '',
  EMAILUSR  varchar(2) default '',
  LANGUAGE varchar(4) default '',
  STARTDATE varchar(30) default '',
  ENDDATE varchar(30) default '',
  EXPIREPASSDATE varchar(30) default '',
  EXPIREDAYS int default '0',
  TRACKCHANGESCOLOR varchar(11) default '',
  LASTLOGONDATE varchar(30) default '',
  ORGANIZATION varchar(255) default '',
  LOCATION varchar(255) default '',
  EXTERNALID varchar(200) default '',
  IMPORTONLOGON  varchar(2) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_USERS_SEQ START WITH 100;
CREATE  INDEX US_USERS on SMART_USERS(USERNAME) ;
CREATE  INDEX FU_USERS on SMART_USERS(FULLNAME) ;
INSERT INTO SMART_USERS (ID, USERNAME, FULLNAME, PASS, DISABLE, FIXEDPASS, EMAIL, EMAILGRP, EMAILUSR, LANGUAGE, STARTDATE, ENDDATE, EXPIREPASSDATE, EXPIREDAYS, TRACKCHANGESCOLOR, LASTLOGONDATE, ORGANIZATION, LOCATION, EXTERNALID, IMPORTONLOGON) VALUES (1, 'woodwing', 'WoodWing Software', '', '', '', '', '', '', 'enUS', '', '', '', 0, '#FF0000', '', '', '', '', '' );

CREATE TABLE SMART_USRGRP (
  ID int ,
  USRID int default '0',
  GRPID int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_USRGRP_SEQ START WITH 100;
CREATE UNIQUE INDEX USGI_USRGRP on SMART_USRGRP(USRID, GRPID) ;
CREATE  INDEX GI_USRGRP on SMART_USRGRP(GRPID) ;
INSERT INTO SMART_USRGRP (ID, USRID, GRPID) VALUES (2, 1, 2);

CREATE TABLE SMART_MTP (
  PUBLID int,
  ISSUEID int default '0',
  LAYTRIGGERSTATE int,
  ARTTRIGGERSTATE int default 0,
  IMGTRIGGERSTATE int default 0,
  LAYPROGSTATE int default 0,
  ARTPROGSTATE int default 0,
  IMGPROGSTATE int default 0,
  MTPTEXT  clob,
  PRIMARY KEY (PUBLID, ISSUEID, LAYTRIGGERSTATE)
);
CREATE  INDEX II_MTP on SMART_MTP(ISSUEID) ;

CREATE TABLE SMART_MTPSENTOBJECTS (
  OBJID int default '0',
  PUBLID int,
  ISSUEID int default '0',
  LAYTRIGGERSTATE int,
  PRINTSTATE int,
  PRIMARY KEY (OBJID, PUBLID, ISSUEID, LAYTRIGGERSTATE, PRINTSTATE)
);
CREATE  INDEX II_MTPSENTOBJECTS on SMART_MTPSENTOBJECTS(ISSUEID) ;
CREATE  INDEX LS_MTPSENTOBJECTS on SMART_MTPSENTOBJECTS(LAYTRIGGERSTATE) ;

CREATE TABLE SMART_MESSAGELOG (
  ID int ,
  OBJID int default 0,
  USERID int default 0,
  MESSAGETYPE varchar(255),
  MESSAGETYPEDETAIL varchar(255),
  MESSAGE  clob,
  DATED varchar(30) default '',
  EXPIRATIONDATE varchar(30) default '',
  MESSAGELEVEL varchar(255) default '',
  FROMUSER varchar(255) default '',
  MSGID varchar(200) default '',
  ANCHORX real default '0',
  ANCHORY real default '0',
  LEFT real default '0',
  TOP real default '0',
  WIDTH real default '0',
  HEIGHT real default '0',
  PAGE int default '0',
  VERSION varchar(200) default '',
  COLOR varchar(11) default '',
  PAGESEQUENCE int default '0',
  THREADMESSAGEID varchar(200) default '',
  REPLYTOMESSAGEID varchar(200) default '',
  MESSAGESTATUS varchar(15) default 'None',
  MAJORVERSION int default '0',
  MINORVERSION int default '0',
  ISREAD varchar(2) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_MESSAGELOG_SEQ START WITH 100;
CREATE  INDEX OIMTPA_MESSAGELOG on SMART_MESSAGELOG(OBJID, MESSAGETYPE, PAGE) ;
CREATE  INDEX OIMTD_MESSAGELOG on SMART_MESSAGELOG(OBJID, MESSAGETYPEDETAIL) ;
CREATE  INDEX MI_MESSAGELOG on SMART_MESSAGELOG(MSGID) ;
CREATE  INDEX UID_MESSAGELOG on SMART_MESSAGELOG(USERID) ;

CREATE TABLE SMART_OBJECTFLAGS (
  OBJID int,
  FLAGORIGIN varchar(255),
  FLAG int,
  SEVERITY int,
  MESSAGE  clob,
  LOCKED int default 0,
  PRIMARY KEY (OBJID, FLAGORIGIN, FLAG)
);

CREATE TABLE SMART_ISSUESECTION (
  ID int ,
  ISSUE int default '0',
  SECTION int default '0',
  DEADLINE varchar(30) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_ISSUESECTION_SEQ START WITH 100;
CREATE  INDEX ISSE_ISSUESECTION on SMART_ISSUESECTION(ISSUE, SECTION) ;

CREATE TABLE SMART_ISSUESECTIONSTATE (
  ID int ,
  ISSUE int default '0',
  SECTION int default '0',
  STATE int default '0',
  DEADLINE varchar(30) default '',
  DEADLINERELATIVE int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_ISSUESECTIONSTATE_SEQ START WITH 100;
CREATE  INDEX ISSEST_ISSUESECTIONSTATE on SMART_ISSUESECTIONSTATE(ISSUE, SECTION, STATE) ;

CREATE TABLE SMART_SECTIONSTATE (
  ID int ,
  SECTION int default '0',
  STATE int default '0',
  DEADLINERELATIVE int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_SECTIONSTATE_SEQ START WITH 100;
CREATE  INDEX SEST_SECTIONSTATE on SMART_SECTIONSTATE(SECTION, STATE) ;

CREATE TABLE SMART_PROFILES (
  ID int ,
  PROFILE varchar(255) default '',
  CODE int default '0',
  DESCRIPTION  clob,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PROFILES_SEQ START WITH 100;
CREATE  INDEX PR_PROFILES on SMART_PROFILES(PROFILE) ;
INSERT INTO SMART_PROFILES (ID, PROFILE, CODE, DESCRIPTION) VALUES (1, 'Full Control', 0, 'All features enabled');

CREATE TABLE SMART_PROFILEFEATURES (
  ID int ,
  PROFILE int default '0',
  FEATURE int default '0',
  VALUE varchar(20) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PROFILEFEATURES_SEQ START WITH 100;
CREATE  INDEX PRFE_PROFILES on SMART_PROFILEFEATURES(PROFILE, FEATURE) ;
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (1, 1, 1, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (2, 1, 2, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (3, 1, 3, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (4, 1, 4, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (5, 1, 5, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (6, 1, 6, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (7, 1, 7, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (8, 1, 8, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (9, 1, 9, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (10, 1, 10, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (11, 1, 99, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (12, 1, 101, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (13, 1, 102, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (14, 1, 103, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (15, 1, 104, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (16, 1, 105, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (17, 1, 106, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (18, 1, 107, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (19, 1, 108, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (20, 1, 109, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (21, 1, 110, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (22, 1, 111, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (23, 1, 112, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (24, 1, 113, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (25, 1, 114, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (26, 1, 115, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (27, 1, 116, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (28, 1, 117, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (29, 1, 118, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (30, 1, 119, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (31, 1, 120, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (32, 1, 121, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (33, 1, 122, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (34, 1, 124, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (35, 1, 125, 'No');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (36, 1, 126, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (37, 1, 127, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (38, 1, 128, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (39, 1, 129, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (40, 1, 130, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (41, 1, 131, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (42, 1, 132, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (43, 1, 133, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (44, 1, 134, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (45, 1, 135, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (46, 1, 1001, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (47, 1, 1002, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (48, 1, 1003, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (49, 1, 1004, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (52, 1, 1007, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (53, 1, 1008, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (54, 1, 91, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (55, 1, 92, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (56, 1, 93, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (57, 1, 90, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (58, 1, 98, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (59, 1, 88, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (61, 1, 87, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (62, 1, 86, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (63, 1, 85, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (64, 1, 1009, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (65, 1, 11, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (66, 1, 12, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (67, 1, 13, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (68, 1, 136, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (69, 1, 70, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (70, 1, 71, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (71, 1, 72, 'Yes');
INSERT INTO SMART_PROFILEFEATURES (ID, PROFILE, FEATURE, VALUE) VALUES (72, 1, 84, 'Yes');

CREATE TABLE SMART_APPSESSIONS (
  ID int ,
  SESSIONID varchar(40) default '',
  USERID varchar(40) default '',
  APPNAME varchar(40) default '',
  LASTSAVED varchar(20) default '',
  READONLY  varchar(2) default '',
  ARTICLEID int default 0,
  ARTICLENAME varchar(255) default '',
  ARTICLEFORMAT varchar(128) default '',
  ARTICLEMINORVERSION int default 0,
  TEMPLATEID int default 0,
  TEMPLATENAME varchar(255) default '',
  TEMPLATEFORMAT varchar(128) default '',
  LAYOUTID int default 0,
  LAYOUTMINORVERSION int default 0,
  ARTICLEMAJORVERSION int default 0,
  LAYOUTMAJORVERSION int default 0,
  DOMMAJORVERSION int default '5',
  DOMMINORVERSION int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_APPSESSIONS_SEQ START WITH 100;

CREATE TABLE SMART_DATASOURCES (
  ID int ,
  TYPE varchar(255) default '',
  NAME varchar(255) default '',
  BIDIRECTIONAL  varchar(2) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_DATASOURCES_SEQ START WITH 100;
CREATE  INDEX NA_DATASOURCES on SMART_DATASOURCES(NAME) ;

CREATE TABLE SMART_DSPUBLICATIONS (
  ID int ,
  DATASOURCEID int default '0',
  PUBLICATIONID int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_DSPUBLICATIONS_SEQ START WITH 100;
CREATE  INDEX DSID_DSPUBLICATIONS on SMART_DSPUBLICATIONS(DATASOURCEID) ;
CREATE  INDEX PUBID_DSPUBLICATIONS on SMART_DSPUBLICATIONS(PUBLICATIONID) ;

CREATE TABLE SMART_DSQUERIES (
  ID int ,
  NAME varchar(255) default '',
  QUERY  clob,
  COMMENTS  clob,
  INTERFACE  clob,
  DATASOURCEID int default '0',
  RECORDID varchar(255) default '',
  RECORDFAMILY varchar(255) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_DSQUERIES_SEQ START WITH 100;
CREATE  INDEX DSID_DSQUERIES on SMART_DSQUERIES(DATASOURCEID) ;

CREATE TABLE SMART_DSQUERYFIELDS (
  ID int ,
  QUERYID int default '0',
  PRIORITY int default '0',
  NAME varchar(255) default '',
  READONLY int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_DSQUERYFIELDS_SEQ START WITH 100;
CREATE  INDEX QUERYID_DSQUERYFIELDS on SMART_DSQUERYFIELDS(QUERYID) ;

CREATE TABLE SMART_DSSETTINGS (
  ID int ,
  NAME varchar(255) default '',
  VALUE  clob,
  DATASOURCEID int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_DSSETTINGS_SEQ START WITH 100;
CREATE  INDEX DSID_DSSETTINGS on SMART_DSSETTINGS(DATASOURCEID) ;

CREATE TABLE SMART_DSQUERYPLACEMENTS (
  ID int ,
  OBJECTID int default '0',
  DATASOURCEID int default '0',
  DIRTY  varchar(2) default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_DSQUERYPLACEMENTS_SEQ START WITH 100;
CREATE  INDEX OBJID_DSQUERYPLACEMENTS on SMART_DSQUERYPLACEMENTS(OBJECTID) ;
CREATE  INDEX DSID_DSQUERYPLACEMENTS on SMART_DSQUERYPLACEMENTS(DATASOURCEID) ;

CREATE TABLE SMART_DSQUERYFAMILIES (
  ID int ,
  QUERYPLACEMENTID int default '0',
  FAMILYFIELD varchar(255) default '',
  FAMILYVALUE  clob,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_DSQUERYFAMILIES_SEQ START WITH 100;

CREATE TABLE SMART_DSUPDATES (
  ID int ,
  RECORDSET blob default '',
  FAMILYVALUE  clob,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_DSUPDATES_SEQ START WITH 100;

CREATE TABLE SMART_DSOBJUPDATES (
  ID int ,
  UPDATEID int default '0',
  OBJECTID int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_DSOBJUPDATES_SEQ START WITH 100;

CREATE TABLE SMART_CHANNELS (
  ID int ,
  NAME varchar(255) default '',
  PUBLICATIONID int default '0',
  TYPE varchar(32) default 'print',
  DESCRIPTION varchar(255) default '',
  CODE int default '0',
  DEADLINERELATIVE int default '0',
  CURRENTISSUEID int default '0',
  PUBLISHSYSTEM varchar(64) default '',
  SUGGESTIONPROVIDER varchar(64) default '',
  PUBLISHSYSTEMID varchar(40) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_CHANNELS_SEQ START WITH 100;
INSERT INTO SMART_CHANNELS (ID, NAME, PUBLICATIONID, TYPE, DESCRIPTION, CODE, DEADLINERELATIVE, CURRENTISSUEID, PUBLISHSYSTEM, SUGGESTIONPROVIDER, PUBLISHSYSTEMID) VALUES (1, 'Print', 1, 'print', 'Print Channel', 10, 0, 1, '', '', '' );
INSERT INTO SMART_CHANNELS (ID, NAME, PUBLICATIONID, TYPE, DESCRIPTION, CODE, DEADLINERELATIVE, CURRENTISSUEID, PUBLISHSYSTEM, SUGGESTIONPROVIDER, PUBLISHSYSTEMID) VALUES (2, 'Web', 1, 'web', 'Web Channel', 20, 0, 0, '', '', '' );

CREATE TABLE SMART_EDITIONS (
  ID int ,
  NAME varchar(255) default '',
  CHANNELID int default '0',
  ISSUEID int default '0',
  CODE int default '0',
  DEADLINERELATIVE int default '0',
  DESCRIPTION  clob,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_EDITIONS_SEQ START WITH 100;
INSERT INTO SMART_EDITIONS (ID, NAME, CHANNELID, ISSUEID, CODE, DEADLINERELATIVE, DESCRIPTION) VALUES (1, 'North', 1, 0, '10', '', '' );
INSERT INTO SMART_EDITIONS (ID, NAME, CHANNELID, ISSUEID, CODE, DEADLINERELATIVE, DESCRIPTION) VALUES (2, 'South', 1, 0, '20', '', '' );

CREATE TABLE SMART_ISSUES (
  ID int ,
  NAME varchar(255) default '',
  CHANNELID int default '0',
  OVERRULEPUB  varchar(2) default '',
  CODE int default '0',
  PUBLDATE varchar(30) default '',
  DEADLINE varchar(30) default '',
  PAGES int default '0',
  SUBJECT  clob,
  DESCRIPTION  clob,
  ACTIVE  varchar(2) default '',
  READINGORDERREV varchar(2) default '',
  CALCULATEDEADLINES  varchar(2) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_ISSUES_SEQ START WITH 100;
CREATE  INDEX CH_ISSUES on SMART_ISSUES(CHANNELID) ;
CREATE  INDEX NA_ISSUES on SMART_ISSUES(NAME) ;
INSERT INTO SMART_ISSUES (ID, NAME, CHANNELID, OVERRULEPUB, CODE, PUBLDATE, DEADLINE, PAGES, SUBJECT, DESCRIPTION, ACTIVE, READINGORDERREV, CALCULATEDEADLINES) VALUES (1, '1st Issue', 1, '', '10', '', '', 16, '', '', 'on', '', '' );
INSERT INTO SMART_ISSUES (ID, NAME, CHANNELID, OVERRULEPUB, CODE, PUBLDATE, DEADLINE, PAGES, SUBJECT, DESCRIPTION, ACTIVE, READINGORDERREV, CALCULATEDEADLINES) VALUES (2, '2nd Issue', 1, '', '20', '', '', 16, '', '', 'on', 'on', '' );
INSERT INTO SMART_ISSUES (ID, NAME, CHANNELID, OVERRULEPUB, CODE, PUBLDATE, DEADLINE, PAGES, SUBJECT, DESCRIPTION, ACTIVE, READINGORDERREV, CALCULATEDEADLINES) VALUES (3, 'webissue', 2, '', '10', '', '', 16, '', '', 'on', 'on', '' );

CREATE TABLE SMART_TARGETS (
  ID int ,
  OBJECTID int default '0',
  CHANNELID int default '0',
  ISSUEID int default '0',
  EXTERNALID varchar(200) default '',
  OBJECTRELATIONID int default '0',
  PUBLISHEDDATE varchar(30) default '',
  PUBLISHEDMAJORVERSION int default '0',
  PUBLISHEDMINORVERSION int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_TARGETS_SEQ START WITH 100;
CREATE UNIQUE INDEX OBCHISOBR_TARGETS on SMART_TARGETS(OBJECTID, CHANNELID, ISSUEID, OBJECTRELATIONID) ;
CREATE UNIQUE INDEX OBROBID_TARGETS on SMART_TARGETS(OBJECTRELATIONID, OBJECTID, ID) ;
CREATE  INDEX ISSUEID_TARGETS on SMART_TARGETS(ISSUEID) ;

CREATE TABLE SMART_PUBLISHHISTORY (
  ID int ,
  EXTERNALID varchar(200) default '',
  OBJECTID int default '0',
  CHANNELID int default '0',
  ISSUEID int default '0',
  EDITIONID int default '0',
  PUBLISHEDDATE varchar(30) default '',
  FIELDS  clob,
  FIELDSMAJORVERSION int default '0',
  FIELDSMINORVERSION int default '0',
  ACTIONDATE varchar(30) default '',
  ACTION varchar(20) default '',
  USERNAME varchar(255) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PUBLISHHISTORY_SEQ START WITH 100;
CREATE  INDEX OBCHIS_PUBLHIST on SMART_PUBLISHHISTORY(OBJECTID, CHANNELID, ISSUEID) ;
CREATE  INDEX CHIS_PUBLHIST on SMART_PUBLISHHISTORY(CHANNELID, ISSUEID) ;

CREATE TABLE SMART_PUBPUBLISHEDISSUES (
  ID int ,
  EXTERNALID varchar(200) default '',
  CHANNELID int default '0',
  ISSUEID int default '0',
  EDITIONID int default '0',
  REPORT  clob,
  DOSSIERORDER  clob,
  PUBLISHDATE varchar(30) default '',
  ISSUEMAJORVERSION int default '0',
  ISSUEMINORVERSION int default '0',
  FIELDS  clob,
  FIELDSMAJORVERSION int default '0',
  FIELDSMINORVERSION int default '0',
  ACTIONDATE varchar(30) default '',
  ACTION varchar(20) default '',
  USERID int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PUBPUBLISHEDISSUES_SEQ START WITH 100;
CREATE  INDEX CHISED_PUBLHIST on SMART_PUBPUBLISHEDISSUES(CHANNELID, ISSUEID, EDITIONID) ;

CREATE TABLE SMART_PUBLISHEDOBJECTSHIST (
  ID int ,
  OBJECTID int default '0',
  PUBLISHID int default '0',
  MAJORVERSION int default '0',
  MINORVERSION int default '0',
  EXTERNALID varchar(200) default '',
  OBJECTNAME varchar(255) default '',
  OBJECTTYPE varchar(40) default '',
  OBJECTFORMAT varchar(128) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PUBLISHEDOBJECTSHIST_SEQ START WITH 100;
CREATE  INDEX OBPU_PUBLOBJHIST on SMART_PUBLISHEDOBJECTSHIST(OBJECTID, PUBLISHID) ;
CREATE  INDEX PUOB_PUBLOBJHIST on SMART_PUBLISHEDOBJECTSHIST(PUBLISHID, OBJECTID) ;

CREATE TABLE SMART_TARGETEDITIONS (
  ID int ,
  TARGETID int default '0',
  EDITIONID int default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_TARGETEDITIONS_SEQ START WITH 100;
CREATE UNIQUE INDEX TAED_TARGETEDITIONS on SMART_TARGETEDITIONS(TARGETID, EDITIONID) ;
CREATE UNIQUE INDEX EDTA_TARGETEDITIONS on SMART_TARGETEDITIONS(EDITIONID, TARGETID) ;

CREATE TABLE SMART_INDESIGNSERVERS (
  ID int ,
  HOSTNAME varchar(64) default '',
  PORTNUMBER int default '0',
  DESCRIPTION varchar(255) default '',
  ACTIVE  varchar(2) default '',
  SERVERMAJORVERSION int default '5',
  SERVERMINORVERSION int default '0',
  PRIO1  varchar(2) default 'on',
  PRIO2  varchar(2) default 'on',
  PRIO3  varchar(2) default 'on',
  PRIO4  varchar(2) default 'on',
  PRIO5  varchar(2) default 'on',
  LOCKTOKEN varchar(40) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_INDESIGNSERVERS_SEQ START WITH 100;
CREATE UNIQUE INDEX HOPO_INDESIGNSERVERS on SMART_INDESIGNSERVERS(HOSTNAME, PORTNUMBER) ;

CREATE TABLE SMART_INDESIGNSERVERJOBS (
  JOBID varchar(40) default '',
  FOREGROUND  varchar(2) default '',
  OBJID int default 0,
  OBJECTMAJORVERSION int default '0',
  OBJECTMINORVERSION int default '0',
  JOBTYPE varchar(32),
  JOBSCRIPT  clob,
  JOBPARAMS  clob,
  LOCKTOKEN varchar(40) default '',
  QUEUETIME varchar(20) default '',
  STARTTIME varchar(30) default '',
  READYTIME varchar(20) default '',
  ERRORCODE varchar(32) default '',
  ERRORMESSAGE varchar(1024) default '',
  SCRIPTRESULT  clob,
  JOBSTATUS int default 0,
  JOBCONDITION int default 0,
  JOBPROGRESS int default 0,
  ATTEMPTS int default 0,
  ASSIGNEDSERVERID int default 0,
  MINSERVERMAJORVERSION int default '0',
  MINSERVERMINORVERSION int default '0',
  MAXSERVERMAJORVERSION int default '0',
  MAXSERVERMINORVERSION int default '0',
  PRIO int default '3',
  TICKETSEAL varchar(40) default '',
  TICKET varchar(40) default '',
  ACTINGUSER varchar(40) default '',
  INITIATOR varchar(40) default '',
  SERVICENAME varchar(32) default '',
  CONTEXT varchar(64) default '',
  PRIMARY KEY (JOBID)
);
CREATE  INDEX ASRE_INDESIGNSERVERJOBS on SMART_INDESIGNSERVERJOBS(ASSIGNEDSERVERID, READYTIME) ;
CREATE  INDEX QT_INDESIGNSERVERJOBS on SMART_INDESIGNSERVERJOBS(QUEUETIME) ;
CREATE  INDEX OBJID_INDESIGNSERVERJOBS on SMART_INDESIGNSERVERJOBS(OBJID) ;
CREATE  INDEX PRID_INDESIGNSERVERJOBS on SMART_INDESIGNSERVERJOBS(PRIO, JOBID) ;
CREATE  INDEX TS_INDESIGNSERVERJOBS on SMART_INDESIGNSERVERJOBS(TICKETSEAL) ;
CREATE  INDEX TTJTSTRT_INDESIGNSERVERJOBS on SMART_INDESIGNSERVERJOBS(TICKET, JOBTYPE, STARTTIME, READYTIME) ;
CREATE  INDEX JP_INDESIGNSERVERJOBS on SMART_INDESIGNSERVERJOBS(JOBPROGRESS) ;
CREATE  INDEX JSPR_INDESIGNSERVERJOBS on SMART_INDESIGNSERVERJOBS(JOBSTATUS, PRIO, QUEUETIME) ;
CREATE  INDEX LT_INDESIGNSERVERJOBS on SMART_INDESIGNSERVERJOBS(LOCKTOKEN) ;

CREATE TABLE SMART_SERVERS (
  ID int ,
  NAME varchar(64) default '',
  TYPE varchar(32) default '',
  URL varchar(1024) default '',
  DESCRIPTION varchar(255) default '',
  JOBSUPPORT  varchar(1) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_SERVERS_SEQ START WITH 100;
CREATE UNIQUE INDEX HOPO_SERVERS on SMART_SERVERS(NAME) ;

CREATE TABLE SMART_SERVERJOBS (
  JOBID varchar(40) default '',
  ATTEMPTS int default 0,
  QUEUETIME varchar(30) default '',
  SERVICENAME varchar(32) default '',
  CONTEXT varchar(32) default '',
  SERVERTYPE varchar(32) default '',
  JOBTYPE varchar(32) default '',
  ASSIGNEDSERVERID int default 0,
  STARTTIME varchar(30) default '0000-00-00T00:00:00',
  READYTIME varchar(30) default '0000-00-00T00:00:00',
  ERRORMESSAGE varchar(1024) default '',
  LOCKTOKEN varchar(40) default '',
  TICKETSEAL varchar(40) default '',
  ACTINGUSER varchar(40) default '',
  JOBSTATUS int default 0,
  JOBCONDITION int default 0,
  JOBPROGRESS int default 0,
  JOBDATA  clob,
  DATAENTITY varchar(20) default '',
  PRIMARY KEY (JOBID)
);
CREATE  INDEX QT_SERVERJOBS on SMART_SERVERJOBS(QUEUETIME) ;
CREATE  INDEX JOBINFO on SMART_SERVERJOBS(LOCKTOKEN, JOBSTATUS, JOBPROGRESS) ;
CREATE  INDEX ASLT_SERVERJOBS on SMART_SERVERJOBS(ASSIGNEDSERVERID, LOCKTOKEN) ;
CREATE  INDEX PAGED_RESULTS on SMART_SERVERJOBS(QUEUETIME, SERVERTYPE, JOBTYPE, JOBSTATUS, ACTINGUSER) ;

CREATE TABLE SMART_SERVERJOBTYPESONHOLD (
  GUID varchar(40) default '',
  JOBTYPE varchar(32) default '',
  RETRYTIMESTAMP varchar(20) default '',
  PRIMARY KEY (GUID)
);
CREATE  INDEX JOBTYPE on SMART_SERVERJOBTYPESONHOLD(JOBTYPE) ;
CREATE  INDEX RETRYTIME on SMART_SERVERJOBTYPESONHOLD(RETRYTIMESTAMP) ;

CREATE TABLE SMART_SERVERJOBCONFIGS (
  ID int ,
  JOBTYPE varchar(32) default '',
  SERVERTYPE varchar(32) default '',
  ATTEMPTS int default 0,
  ACTIVE  varchar(1) default 'N',
  SYSADMIN  varchar(1) default '-',
  USERID int default 0,
  USERCONFIGNEEDED  varchar(1) default 'Y',
  RECURRING  varchar(1) default 'N',
  SELFDESTRUCTIVE  varchar(1) default 'N',
  WORKINGDAYS  varchar(1) default 'N',
  DAILYSTARTTIME varchar(30) default '00-00-00T00:00:00',
  DAILYSTOPTIME varchar(30) default '00-00-00T00:00:00',
  TIMEINTERVAL int default 0,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_SERVERJOBCONFIGS_SEQ START WITH 100;

CREATE TABLE SMART_SERVERJOBSUPPORTS (
  ID int ,
  SERVERID int default 0,
  JOBCONFIGID int default 0,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_SERVERJOBSUPPORTS_SEQ START WITH 100;
CREATE UNIQUE INDEX SJS_SERVERCONFIGS on SMART_SERVERJOBSUPPORTS(SERVERID, JOBCONFIGID) ;

CREATE TABLE SMART_SERVERPLUGINS (
  ID int ,
  UNIQUENAME varchar(64) default '',
  DISPLAYNAME varchar(128) default '',
  VERSION varchar(64) default '',
  DESCRIPTION varchar(255) default '',
  COPYRIGHT varchar(128) default '',
  ACTIVE  varchar(2) default '',
  SYSTEM  varchar(2) default '',
  INSTALLED  varchar(2) default '',
  MODIFIED varchar(30) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_SERVERPLUGINS_SEQ START WITH 100;
INSERT INTO SMART_SERVERPLUGINS (ID, UNIQUENAME, DISPLAYNAME, VERSION, DESCRIPTION, COPYRIGHT, ACTIVE, SYSTEM, INSTALLED, MODIFIED) VALUES (1, 'PreviewMetaPHP', 'PHP Preview and Meta Data', 'v6.1', 'Using internal PHP libraries (such as GD) to generate previews and read metadata', '(c) 1998-2008 WoodWing Software bv. All rights reserved.', 'on', 'on', 'on', '2008-10-02T09:00:00');
INSERT INTO SMART_SERVERPLUGINS (ID, UNIQUENAME, DISPLAYNAME, VERSION, DESCRIPTION, COPYRIGHT, ACTIVE, SYSTEM, INSTALLED, MODIFIED) VALUES (2, 'ImageMagick', 'ImageMagick', 'v6.1', 'Use ImageMagick to support extra formats for preview generation', '(c) 1998-2008 WoodWing Software bv. All rights reserved.', '', 'on', '', '2008-10-02T09:00:00');
INSERT INTO SMART_SERVERPLUGINS (ID, UNIQUENAME, DISPLAYNAME, VERSION, DESCRIPTION, COPYRIGHT, ACTIVE, SYSTEM, INSTALLED, MODIFIED) VALUES (3, 'InCopyHTMLConversion', 'InCopy HTML Conversion', 'v6.1', 'Have InCopy and InDesign edit HTML articles by converting the article to text', '(c) 1998-2008 WoodWing Software bv. All rights reserved.', 'on', 'on', 'on', '2008-11-30T09:00:00');

CREATE TABLE SMART_SERVERCONNECTORS (
  ID int ,
  PLUGINID int default '0',
  CLASSNAME varchar(128) default '',
  INTERFACE varchar(128) default '',
  TYPE varchar(32) default '',
  PRIO int default '0',
  RUNMODE varchar(16) default '',
  CLASSFILE varchar(255) default '',
  MODIFIED varchar(30) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_SERVERCONNECTORS_SEQ START WITH 100;
CREATE  INDEX SECO_PLUGINID on SMART_SERVERCONNECTORS(PLUGINID) ;
CREATE  INDEX SECO_TYPEINTERFACE on SMART_SERVERCONNECTORS(TYPE, INTERFACE) ;
INSERT INTO SMART_SERVERCONNECTORS (ID, PLUGINID, CLASSNAME, INTERFACE, TYPE, PRIO, RUNMODE, CLASSFILE, MODIFIED) VALUES (1, 1, 'PreviewMetaPHP_Preview', 'Preview', '', 500, 'Synchron', '/server/plugins/PreviewMetaPHP/PreviewMetaPHP_Preview.class.php', '2008-10-02T09:00:00');
INSERT INTO SMART_SERVERCONNECTORS (ID, PLUGINID, CLASSNAME, INTERFACE, TYPE, PRIO, RUNMODE, CLASSFILE, MODIFIED) VALUES (2, 1, 'PreviewMetaPHP_MetaData', 'MetaData', '', 500, 'Synchron', '/server/plugins/PreviewMetaPHP/PreviewMetaPHP_MetaData.class.php', '2008-10-02T09:00:00');
INSERT INTO SMART_SERVERCONNECTORS (ID, PLUGINID, CLASSNAME, INTERFACE, TYPE, PRIO, RUNMODE, CLASSFILE, MODIFIED) VALUES (3, 3, 'InCopyHTMLConversion_WflGetObjects', 'WflGetObjects', 'WorkflowService', 500, 'After', '/server/plugins/InCopyHTMLConversion/InCopyHTMLConversion_WflGetObjects.class.php', '2008-11-30T09:00:00');

CREATE TABLE SMART_SEMAPHORES (
  ID int ,
  ENTITYID varchar(40) default '0',
  LASTUPDATE int default '0',
  LIFETIME int default '0',
  USERNAME varchar(40) default '',
  IP varchar(30) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_SEMAPHORES_SEQ START WITH 100;
CREATE UNIQUE INDEX IDX_ENTITY on SMART_SEMAPHORES(ENTITYID) ;
CREATE  INDEX IDX_ENTITYUSER on SMART_SEMAPHORES(ENTITYID, USERNAME) ;

CREATE TABLE SMART_OUTPUTDEVICES (
  ID int ,
  NAME varchar(255) default '',
  CODE int default '0',
  DESCRIPTION  clob,
  LANDSCAPEWIDTH int default '0',
  LANDSCAPEHEIGHT int default '0',
  PORTRAITWIDTH int default '0',
  PORTRAITHEIGHT int default '0',
  PREVIEWQUALITY int default '0',
  LANDSCAPELAYOUTWIDTH real default '0',
  PIXELDENSITY int default '0',
  PNGCOMPRESSION int default '0',
  TEXTVIEWPADDING varchar(50) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_OUTPUTDEVICES_SEQ START WITH 100;
INSERT INTO SMART_OUTPUTDEVICES (ID, NAME, CODE, DESCRIPTION, LANDSCAPEWIDTH, LANDSCAPEHEIGHT, PORTRAITWIDTH, PORTRAITHEIGHT, PREVIEWQUALITY, LANDSCAPELAYOUTWIDTH, PIXELDENSITY, PNGCOMPRESSION, TEXTVIEWPADDING) VALUES (1, 'iPad - DM', 0, '', 1024, 748, 768, 1004, 4, 558.5, 132, 9, '');
INSERT INTO SMART_OUTPUTDEVICES (ID, NAME, CODE, DESCRIPTION, LANDSCAPEWIDTH, LANDSCAPEHEIGHT, PORTRAITWIDTH, PORTRAITHEIGHT, PREVIEWQUALITY, LANDSCAPELAYOUTWIDTH, PIXELDENSITY, PNGCOMPRESSION, TEXTVIEWPADDING) VALUES (2, 'iPad', 10, '', 1024, 768, 768, 1024, 4, 1024, 132, 9, '');
INSERT INTO SMART_OUTPUTDEVICES (ID, NAME, CODE, DESCRIPTION, LANDSCAPEWIDTH, LANDSCAPEHEIGHT, PORTRAITWIDTH, PORTRAITHEIGHT, PREVIEWQUALITY, LANDSCAPELAYOUTWIDTH, PIXELDENSITY, PNGCOMPRESSION, TEXTVIEWPADDING) VALUES (3, 'Kindle Fire', 20, '', 1024, 600, 600, 1024, 4, 1024, 169, 9, '');
INSERT INTO SMART_OUTPUTDEVICES (ID, NAME, CODE, DESCRIPTION, LANDSCAPEWIDTH, LANDSCAPEHEIGHT, PORTRAITWIDTH, PORTRAITHEIGHT, PREVIEWQUALITY, LANDSCAPELAYOUTWIDTH, PIXELDENSITY, PNGCOMPRESSION, TEXTVIEWPADDING) VALUES (4, 'Xoom', 30, '', 1280, 800, 800, 1280, 4, 1280, 160, 9, '');

CREATE TABLE SMART_PLACEMENTTILES (
  ID int ,
  PLACEMENTID int default '0',
  PAGESEQUENCE int default '0',
  LEFT real default '0',
  TOP real default '0',
  WIDTH real default '0',
  HEIGHT real default '0',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_PLACEMENTTILES_SEQ START WITH 100;
CREATE  INDEX PI_PLACEMENTTILES on SMART_PLACEMENTTILES(PLACEMENTID) ;

CREATE TABLE SMART_OBJECTLABELS (
  ID int ,
  OBJID int default '0',
  NAME varchar(250) default '',
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SMART_OBJECTLABELS_SEQ START WITH 100;
CREATE  INDEX OBJLABELS_OBJID on SMART_OBJECTLABELS(OBJID) ;

CREATE TABLE SMART_OBJECTRELATIONLABELS (
  LABELID int default '0',
  CHILDOBJID int default '0',
  PRIMARY KEY (LABELID, CHILDOBJID)
);
CREATE  INDEX OBJRELLABELS_CHILDOBJID on SMART_OBJECTRELATIONLABELS(CHILDOBJID) ;
CREATE GLOBAL TEMPORARY TABLE TEMP_AOV (
  ID int ,
  PRIMARY KEY (ID)
) ON COMMIT PRESERVE ROWS ;
CREATE GLOBAL TEMPORARY TABLE TEMP_CV0 (
  ID int ,
  PRIMARY KEY (ID)
) ON COMMIT PRESERVE ROWS ;
CREATE GLOBAL TEMPORARY TABLE TEMP_CV1 (
  ID int ,
  PRIMARY KEY (ID)
) ON COMMIT PRESERVE ROWS ;
CREATE GLOBAL TEMPORARY TABLE TEMP_CV2 (
  ID int ,
  PRIMARY KEY (ID)
) ON COMMIT PRESERVE ROWS ;
CREATE GLOBAL TEMPORARY TABLE TEMP_CV3 (
  ID int ,
  PRIMARY KEY (ID)
) ON COMMIT PRESERVE ROWS ;
CREATE GLOBAL TEMPORARY TABLE TEMP_CV4 (
  ID int ,
  PRIMARY KEY (ID)
) ON COMMIT PRESERVE ROWS ;
CREATE GLOBAL TEMPORARY TABLE TEMP_CV9 (
  ID int ,
  PRIMARY KEY (ID)
) ON COMMIT PRESERVE ROWS ;
CREATE GLOBAL TEMPORARY TABLE TEMP_TVI (
  ID int ,
  PRIMARY KEY (ID)
) ON COMMIT PRESERVE ROWS ;
CREATE GLOBAL TEMPORARY TABLE TEMP_AV (
  PUBLICATION int ,
  ISSUE int ,
  SECTION int ,
  STATE int ,
  PRIMARY KEY (PUBLICATION, ISSUE, SECTION, STATE)
) ON COMMIT PRESERVE ROWS ;
CREATE  INDEX ISPUSEST on TEMP_AV(ISSUE, PUBLICATION, SECTION, STATE) ;

CREATE TABLE SMART_CHANNELDATA (
  PUBLICATION int default '0',
  PUBCHANNEL int default '0',
  ISSUE int default '0',
  SECTION int default '0',
  NAME varchar(200) default '',
  VALUE  clob,
  PRIMARY KEY (PUBLICATION, PUBCHANNEL, ISSUE, SECTION, NAME)
);
CREATE GLOBAL TEMPORARY TABLE TEMP_CV10 (
  ID int ,
  PRIMARY KEY (ID)
) ON COMMIT PRESERVE ROWS ;
CREATE GLOBAL TEMPORARY TABLE TEMP_CV11 (
  ID int ,
  PRIMARY KEY (ID)
) ON COMMIT PRESERVE ROWS ;
CREATE GLOBAL TEMPORARY TABLE TEMP_CV12 (
  ID int ,
  PRIMARY KEY (ID)
) ON COMMIT PRESERVE ROWS ;
UPDATE SMART_CONFIG set VALUE = '10.1' where NAME = 'version';

grant select on SMART_ACTIONPROPERTIES_SEQ to woodwing;
grant select,insert,update,delete on SMART_ACTIONPROPERTIES to woodwing;
grant select on SMART_AUTHORIZATIONS_SEQ to woodwing;
grant select,insert,update,delete on SMART_AUTHORIZATIONS to woodwing;
grant select on SMART_CONFIG_SEQ to woodwing;
grant select,insert,update,delete on SMART_CONFIG to woodwing;
grant select on SMART_DELETEDOBJECTS_SEQ to woodwing;
grant select,insert,update,delete on SMART_DELETEDOBJECTS to woodwing;
grant select on SMART_GROUPS_SEQ to woodwing;
grant select,insert,update,delete on SMART_GROUPS to woodwing;
grant select on SMART_LOG_SEQ to woodwing;
grant select,insert,update,delete on SMART_LOG to woodwing;
grant select on SMART_NAMEDQUERIES_SEQ to woodwing;
grant select,insert,update,delete on SMART_NAMEDQUERIES to woodwing;
grant select on SMART_OBJECTLOCKS_SEQ to woodwing;
grant select,insert,update,delete on SMART_OBJECTLOCKS to woodwing;
grant select on SMART_OBJECTRELATIONS_SEQ to woodwing;
grant select,insert,update,delete on SMART_OBJECTRELATIONS to woodwing;
grant select on SMART_OBJECTS_SEQ to woodwing;
grant select,insert,update,delete on SMART_OBJECTS to woodwing;
grant select on SMART_OBJECTVERSIONS_SEQ to woodwing;
grant select,insert,update,delete on SMART_OBJECTVERSIONS to woodwing;
grant select on SMART_OBJECTRENDITIONS_SEQ to woodwing;
grant select,insert,update,delete on SMART_OBJECTRENDITIONS to woodwing;
grant select on SMART_PAGES_SEQ to woodwing;
grant select,insert,update,delete on SMART_PAGES to woodwing;
grant select on SMART_PLACEMENTS_SEQ to woodwing;
grant select,insert,update,delete on SMART_PLACEMENTS to woodwing;
grant select on SMART_ELEMENTS_SEQ to woodwing;
grant select,insert,update,delete on SMART_ELEMENTS to woodwing;
grant select,insert,update,delete on SMART_INDESIGNARTICLES to woodwing;
grant select,insert,update,delete on SMART_IDARTICLESPLACEMENTS to woodwing;
grant select on SMART_OBJECTOPERATIONS_SEQ to woodwing;
grant select,insert,update,delete on SMART_OBJECTOPERATIONS to woodwing;
grant select on SMART_PROPERTIES_SEQ to woodwing;
grant select,insert,update,delete on SMART_PROPERTIES to woodwing;
grant select on SMART_PUBLADMIN_SEQ to woodwing;
grant select,insert,update,delete on SMART_PUBLADMIN to woodwing;
grant select on SMART_PUBLICATIONS_SEQ to woodwing;
grant select,insert,update,delete on SMART_PUBLICATIONS to woodwing;
grant select on SMART_PUBLSECTIONS_SEQ to woodwing;
grant select,insert,update,delete on SMART_PUBLSECTIONS to woodwing;
grant select on SMART_PUBLOBJECTS_SEQ to woodwing;
grant select,insert,update,delete on SMART_PUBLOBJECTS to woodwing;
grant select on SMART_ISSUEEDITIONS_SEQ to woodwing;
grant select,insert,update,delete on SMART_ISSUEEDITIONS to woodwing;
grant select on SMART_ROUTING_SEQ to woodwing;
grant select,insert,update,delete on SMART_ROUTING to woodwing;
grant select on SMART_SETTINGS_SEQ to woodwing;
grant select,insert,update,delete on SMART_SETTINGS to woodwing;
grant select on SMART_STATES_SEQ to woodwing;
grant select,insert,update,delete on SMART_STATES to woodwing;
grant select on SMART_TICKETS_SEQ to woodwing;
grant select,insert,update,delete on SMART_TICKETS to woodwing;
grant select on SMART_TERMENTITIES_SEQ to woodwing;
grant select,insert,update,delete on SMART_TERMENTITIES to woodwing;
grant select,insert,update,delete on SMART_TERMS to woodwing;
grant select on SMART_USERS_SEQ to woodwing;
grant select,insert,update,delete on SMART_USERS to woodwing;
grant select on SMART_USRGRP_SEQ to woodwing;
grant select,insert,update,delete on SMART_USRGRP to woodwing;
grant select,insert,update,delete on SMART_MTP to woodwing;
grant select,insert,update,delete on SMART_MTPSENTOBJECTS to woodwing;
grant select on SMART_MESSAGELOG_SEQ to woodwing;
grant select,insert,update,delete on SMART_MESSAGELOG to woodwing;
grant select,insert,update,delete on SMART_OBJECTFLAGS to woodwing;
grant select on SMART_ISSUESECTION_SEQ to woodwing;
grant select,insert,update,delete on SMART_ISSUESECTION to woodwing;
grant select on SMART_ISSUESECTIONSTATE_SEQ to woodwing;
grant select,insert,update,delete on SMART_ISSUESECTIONSTATE to woodwing;
grant select on SMART_SECTIONSTATE_SEQ to woodwing;
grant select,insert,update,delete on SMART_SECTIONSTATE to woodwing;
grant select on SMART_PROFILES_SEQ to woodwing;
grant select,insert,update,delete on SMART_PROFILES to woodwing;
grant select on SMART_PROFILEFEATURES_SEQ to woodwing;
grant select,insert,update,delete on SMART_PROFILEFEATURES to woodwing;
grant select on SMART_APPSESSIONS_SEQ to woodwing;
grant select,insert,update,delete on SMART_APPSESSIONS to woodwing;
grant select on SMART_DATASOURCES_SEQ to woodwing;
grant select,insert,update,delete on SMART_DATASOURCES to woodwing;
grant select on SMART_DSPUBLICATIONS_SEQ to woodwing;
grant select,insert,update,delete on SMART_DSPUBLICATIONS to woodwing;
grant select on SMART_DSQUERIES_SEQ to woodwing;
grant select,insert,update,delete on SMART_DSQUERIES to woodwing;
grant select on SMART_DSQUERYFIELDS_SEQ to woodwing;
grant select,insert,update,delete on SMART_DSQUERYFIELDS to woodwing;
grant select on SMART_DSSETTINGS_SEQ to woodwing;
grant select,insert,update,delete on SMART_DSSETTINGS to woodwing;
grant select on SMART_DSQUERYPLACEMENTS_SEQ to woodwing;
grant select,insert,update,delete on SMART_DSQUERYPLACEMENTS to woodwing;
grant select on SMART_DSQUERYFAMILIES_SEQ to woodwing;
grant select,insert,update,delete on SMART_DSQUERYFAMILIES to woodwing;
grant select on SMART_DSUPDATES_SEQ to woodwing;
grant select,insert,update,delete on SMART_DSUPDATES to woodwing;
grant select on SMART_DSOBJUPDATES_SEQ to woodwing;
grant select,insert,update,delete on SMART_DSOBJUPDATES to woodwing;
grant select on SMART_CHANNELS_SEQ to woodwing;
grant select,insert,update,delete on SMART_CHANNELS to woodwing;
grant select on SMART_EDITIONS_SEQ to woodwing;
grant select,insert,update,delete on SMART_EDITIONS to woodwing;
grant select on SMART_ISSUES_SEQ to woodwing;
grant select,insert,update,delete on SMART_ISSUES to woodwing;
grant select on SMART_TARGETS_SEQ to woodwing;
grant select,insert,update,delete on SMART_TARGETS to woodwing;
grant select on SMART_PUBLISHHISTORY_SEQ to woodwing;
grant select,insert,update,delete on SMART_PUBLISHHISTORY to woodwing;
grant select on SMART_PUBPUBLISHEDISSUES_SEQ to woodwing;
grant select,insert,update,delete on SMART_PUBPUBLISHEDISSUES to woodwing;
grant select on SMART_PUBLISHEDOBJECTSHIST_SEQ to woodwing;
grant select,insert,update,delete on SMART_PUBLISHEDOBJECTSHIST to woodwing;
grant select on SMART_TARGETEDITIONS_SEQ to woodwing;
grant select,insert,update,delete on SMART_TARGETEDITIONS to woodwing;
grant select on SMART_INDESIGNSERVERS_SEQ to woodwing;
grant select,insert,update,delete on SMART_INDESIGNSERVERS to woodwing;
grant select,insert,update,delete on SMART_INDESIGNSERVERJOBS to woodwing;
grant select on SMART_SERVERS_SEQ to woodwing;
grant select,insert,update,delete on SMART_SERVERS to woodwing;
grant select,insert,update,delete on SMART_SERVERJOBS to woodwing;
grant select,insert,update,delete on SMART_SERVERJOBTYPESONHOLD to woodwing;
grant select on SMART_SERVERJOBCONFIGS_SEQ to woodwing;
grant select,insert,update,delete on SMART_SERVERJOBCONFIGS to woodwing;
grant select on SMART_SERVERJOBSUPPORTS_SEQ to woodwing;
grant select,insert,update,delete on SMART_SERVERJOBSUPPORTS to woodwing;
grant select on SMART_SERVERPLUGINS_SEQ to woodwing;
grant select,insert,update,delete on SMART_SERVERPLUGINS to woodwing;
grant select on SMART_SERVERCONNECTORS_SEQ to woodwing;
grant select,insert,update,delete on SMART_SERVERCONNECTORS to woodwing;
grant select on SMART_SEMAPHORES_SEQ to woodwing;
grant select,insert,update,delete on SMART_SEMAPHORES to woodwing;
grant select on SMART_OUTPUTDEVICES_SEQ to woodwing;
grant select,insert,update,delete on SMART_OUTPUTDEVICES to woodwing;
grant select on SMART_PLACEMENTTILES_SEQ to woodwing;
grant select,insert,update,delete on SMART_PLACEMENTTILES to woodwing;
grant select on SMART_OBJECTLABELS_SEQ to woodwing;
grant select,insert,update,delete on SMART_OBJECTLABELS to woodwing;
grant select,insert,update,delete on SMART_OBJECTRELATIONLABELS to woodwing;
grant select,insert,update,delete on TEMP_AOV to woodwing;
grant select,insert,update,delete on TEMP_CV0 to woodwing;
grant select,insert,update,delete on TEMP_CV1 to woodwing;
grant select,insert,update,delete on TEMP_CV2 to woodwing;
grant select,insert,update,delete on TEMP_CV3 to woodwing;
grant select,insert,update,delete on TEMP_CV4 to woodwing;
grant select,insert,update,delete on TEMP_CV9 to woodwing;
grant select,insert,update,delete on TEMP_TVI to woodwing;
grant select,insert,update,delete on TEMP_AV to woodwing;
grant select,insert,update,delete on SMART_CHANNELDATA to woodwing;
grant select,insert,update,delete on TEMP_CV10 to woodwing;
grant select,insert,update,delete on TEMP_CV11 to woodwing;
grant select,insert,update,delete on TEMP_CV12 to woodwing;
