<?php
/**
 * @package Enterprise
 * @subpackage DataClasses
 * @since v9.7.0 stdClass is changed into InDesignServer
 * @copyright WoodWing Software bv. All Rights Reserved.
 *
 * InDesign Server configuration.
 */

class InDesignServer
{
	public $Id;            // DB record id of the configured IDS instance.
	public $HostName;      // HTTP URL of the machine this IDS instance is running at.
	public $PortNumber;    // HTTP port this IDS instance is listening for SOAP messages.
	public $Description;   // Extra information for IDS instance, shown in the admin pages.
	public $Active;        // Whether or not this instance should handle jobs at all.
	public $Prio1;         // Whether or not this instance should handle prio 5 jobs.
	public $Prio2;         // Whether or not this instance should handle prio 5 jobs.
	public $Prio3;         // Whether or not this instance should handle prio 5 jobs.
	public $Prio4;         // Whether or not this instance should handle prio 5 jobs.
	public $Prio5;         // Whether or not this instance should handle prio 5 jobs.
	public $ServerVersion; // Internal InDesign Server major version; 8=CS6, 10=CC2014, etc
	public $LockToken;     // [9.7] GUID generated by a PHP process to assure it took the lock to pick the IDS instance (blocking other processes accidentally picking same IDS instance at the same time).
}
