CREATE SEQUENCE {DBPREFIX}AXAIO_MTP_TRIGGER_SEQ START WITH 100;
CREATE TABLE {DBPREFIX}AXAIO_MTP_TRIGGER (
  PUBLICATION_ID int,
  ISSUE_ID int default '0',
  STATE_TRIGGER_LAYOUT int,
  STATE_TRIGGER_ARTICLE int default 0,
  STATE_TRIGGER_IMAGE int default 0,
  STATE_AFTER_LAYOUT int default 0,
  STATE_AFTER_ARTICLE int default 0,
  STATE_AFTER_IMAGE int default 0,
  MTP_JOBNAME  clob,
  PRIMARY KEY (PUBLICATION_ID, ISSUE_ID, STATE_TRIGGER_LAYOUT, STATE_TRIGGER_ARTICLE, STATE_TRIGGER_IMAGE)
);
CREATE  INDEX II_MTP on {DBPREFIX}AXAIO_MTP_TRIGGER(ISSUE_ID) ;
CREATE SEQUENCE {DBPREFIX}AXAIO_MTP_SENTOBJECTS_SEQ START WITH 100;
CREATE TABLE {DBPREFIX}AXAIO_MTP_SENTOBJECTS (
  OBJID int default '0',
  PUBLID int,
  ISSUEID int default '0',
  LAYTRIGGERSTATE int,
  PRINTSTATE int,
  PRIMARY KEY (OBJID, PUBLID, ISSUEID, LAYTRIGGERSTATE, PRINTSTATE)
);
CREATE  INDEX II_MTPSENTOBJECTS on {DBPREFIX}AXAIO_MTP_SENTOBJECTS(ISSUEID) ;
CREATE  INDEX LS_MTPSENTOBJECTS on {DBPREFIX}AXAIO_MTP_SENTOBJECTS(LAYTRIGGERSTATE) ;
CREATE TABLE {DBPREFIX}AXAIO_MTP_PROCESS_OPTIONS (
  ID int,
  OPTION_NAME clob,
  OPTION_VALUE clob default '',
  PRIMARY KEY (ID)
);
