
drop synonym woodwing.{DBPREFIX}AXAIO_MTP_TRIGGER_SEQ;

create synonym woodwing.{DBPREFIX}AXAIO_MTP_TRIGGER_SEQ for root.{DBPREFIX}AXAIO_MTP_TRIGGER_SEQ;

drop synonym woodwing.{DBPREFIX}AXAIO_MTP_TRIGGER;

create synonym woodwing.{DBPREFIX}AXAIO_MTP_TRIGGER for root.{DBPREFIX}AXAIO_MTP_TRIGGER;



drop synonym woodwing.{DBPREFIX}AXAIO_MTP_SENTOBJECTS_SEQ;

create synonym woodwing.{DBPREFIX}AXAIO_MTP_SENTOBJECTS_SEQ for root.{DBPREFIX}AXAIO_MTP_SENTOBJECTS_SEQ;

drop synonym woodwing.{DBPREFIX}AXAIO_MTP_SENTOBJECTS;

create synonym woodwing.{DBPREFIX}AXAIO_MTP_SENTOBJECTS for root.{DBPREFIX}AXAIO_MTP_SENTOBJECTS;




drop synonym woodwing.{DBPREFIX}AXAIO_MTP_PROCESS_OPTIONS_SEQ;

create synonym woodwing.{DBPREFIX}AXAIO_MTP_PROCESS_OPTIONS_SEQ for root.{DBPREFIX}AXAIO_MTP_PROCESS_OPTIONS_SEQ;

drop synonym woodwing.{DBPREFIX}AXAIO_MTP_PROCESS_OPTIONS;

create synonym woodwing.{DBPREFIX}AXAIO_MTP_PROCESS_OPTIONS for root.{DBPREFIX}AXAIO_MTP_PROCESS_OPTIONS;

